
- hosts: all
  become: true
  vars:
     human_name: "Spencer Krum"
  tasks:
  - name: ensure apache is at the latest version
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == 'Debian'
  - name: ensure apache is at the latest version
    apt:
      name: httpd
      state: latest
    when: ansible_os_family == 'RedHat'
  - name: manage apache service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == 'RedHat'
  - name: manage apache service
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == 'Debian'
  - name: ensure mod wsgi is at the latest version
    apt:
      name: libapache2-mod-wsgi
      state: latest
    when: ansible_os_family == 'Debian'
  - name: ensure mod wsgi is at the latest version
    apt:
      name: mod_wsgi
      state: latest
    when: ansible_os_family == 'RedHat'
  - name: enable mod_wsgi
    apache2_module:
      state: present
      name: wsgi
    notify:
    - restart apache
  - name: manage main web page
    template:
      src: hello_world.html.j2
      dest: /var/www/html/index.html
      mode: 0644
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
      when: ansible_os_family == 'Debian'
    - name: restart apache
      service: name=httpd state=restarted
      when: ansible_os_family == 'RedHat'
